# Generated by Django 5.0.4 on 2024-04-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_query"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Query",
        ),
    ]
