# Generated by Django 5.0.4 on 2024-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
